# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638dcbbf602ab55ddc3d235182c52b5a1f450e781d34c6e8d8a84f5718f1cc385a8b35d31819fcd3ce3db9d5f2cb6281b4eaf3247979398ccf25918fd98d5639

test:
  secret_key_base: 30ab24e6d2ce66a5cec0b931a742b051eba58351ddf4a3569da8319288552c34c0a053d8d46b4be303e61e3081aee702079e5e449c60b36acaeb9c740c33aad8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
